server:
  port: 8080
spring:
  application:
    name: lyp_admin
  main:
    allow-bean-definition-overriding: true
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    #   Druid连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/lyp_chat?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
    druid:
      url: jdbc:mysql://localhost:3306/lyp_chat?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      initial-size: 2
      min-idle: 5
      max-active: 10
      max-wait: 5000
      validation-query: SELECT 1
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  redis:
    database: 0
    port: 6379
    host: localhost
eureka:
  client:
    service-url:
      defaultZone: http://47.100.246.42:10086/eureka/
  instance:
    prefer-ip-address: true
